title: Promobot Education
logo: /assets/img/logo.png
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
github_home_url: https://github.com/promobot-education
robox_url: /Robox
rooky_url: /Rooky
rrstudio_url: /RRStudio
test_devices_url: /TestDevices
V4_url: /V4
WSL2_url: /WSL2
support_telegram_url: https://t.me/PromobotSupportBot
